wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1657259293
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      4: 3.9.12
      5: 0.12.20
      8:
      - 1
      - 8
      - 9
env:
  desc: null
  value: Taxi-v3
framework:
  desc: null
  value: torch
num_cpu:
  desc: null
  value: 5
num_cpu_workers:
  desc: null
  value: 10
num_gpus:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 1
record_env:
  desc: null
  value: true
